### ISSUE TITLE
gradle 6.x hello world失败

### ISSUE THREAD

**Issue by wjx0912** [DONGChuan/GradleUserGuide#33]
> 
    task hello << {
        println 'Hello world!'
    }

这是教程里面的例子，是什么错误呢？

**Comment by yangxiaobinhaoshuai** [comment]
自 Gradle 5.0 开始 left shift 操作符已经被 remove 了，需要显示调用 doLast。

yongjian <notifications@github.com> 于2020年1月14日周二 上午10:10写道：

**Comment by wjx0912** [comment]
@yangxiaobinhaoshuai 
谢谢了。教程能不能更新一下呢，新手看到这里会比较困惑。

**Comment by yangxiaobinhaoshuai** [comment]
很抱歉不能及时更新文档，Gradle release 十分频繁，翻译颇具工作量，由于工作问题没有时间来更新文档，见谅。

yongjian <notifications@github.com> 于2020年1月14日周二 上午10:18写道：
